import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { ArrowRight, ArrowUpRight, AudioLines, Bell, Bot, CalendarDays, Check, ChevronDown, CircleHelp, Clock3, Code2, Command, GitBranch, Headphones, Inbox, Instagram, Layers3, LayoutDashboard, Mail, Menu, MessageCircle, MessagesSquare, PanelLeft, PhoneCall, Search, Send, Settings2, ShieldCheck, Sparkles, Tag, Users, Webhook, X, Zap, BarChart3, KanbanSquare, ListFilter, PlugZap, Radio, Workflow, Megaphone, BriefcaseBusiness, ShoppingBag, Store, Globe2, UserRoundCheck } from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "SharkZapp | Atendimento e Automação Multicanal" },
      { name: "description", content: "Centralize WhatsApp, Instagram, Mercado Livre e outros canais. Automatize seu atendimento, organize sua equipe e gerencie sua operação em um só lugar com a SharkZapp." },
      { property: "og:title", content: "SharkZapp | Atendimento e Automação Multicanal" },
      { property: "og:description", content: "Centralize WhatsApp, Instagram, Mercado Livre e outros canais. Automatize seu atendimento, organize sua equipe e gerencie sua operação em um só lugar com a SharkZapp." },
      { property: "og:type", content: "website" },
      { property: "og:url", content: "/" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
    links: [{ rel: "canonical", href: "/" }],
  }),
  component: Landing,
});

const nav = [
  ["Início", "#inicio"], ["Funcionalidades", "#funcionalidades"], ["Canais", "#canais"],
  ["Como funciona", "#como-funciona"], ["Planos", "#planos"], ["FAQ", "#faq"],
] as const;
const channels = ["WhatsApp", "Instagram", "Mercado Livre", "Messenger", "Telegram", "E-mail", "Webchat", "TikTok", "YouTube", "OLX"];
const features: [string, string, LucideIcon][] = [
  ["Multiatendimento", "Conversas distribuídas entre atendentes.", Users], ["Inbox unificado", "Uma visão clara dos seus canais.", Inbox],
  ["Chatbots", "Fluxos para as primeiras interações.", Bot], ["Inteligência Artificial", "Apoio inteligente para sua equipe.", Sparkles],
  ["CRM", "Contatos e oportunidades organizados.", KanbanSquare], ["Automações", "Ações acionadas no momento certo.", Workflow],
  ["Campanhas", "Comunicações em uma operação organizada.", Megaphone], ["Agendamento", "Planeje ações e acompanhamentos.", CalendarDays],
  ["API", "Conecte processos ao seu ecossistema.", Code2], ["Webhooks", "Eventos conectados a outros sistemas.", Webhook],
  ["Relatórios", "Acompanhe a rotina da operação.", BarChart3], ["Gestão de equipe", "Organize pessoas e responsabilidades.", UserRoundCheck],
  ["Etiquetas", "Identifique conversas rapidamente.", Tag], ["Filas", "Direcione cada atendimento.", ListFilter],
  ["Setores", "Separe fluxos por área.", Layers3], ["Histórico de conversas", "Contexto para cada interação.", MessagesSquare],
];
const faqs = [
  ["O que é a SharkZapp?", "A SharkZapp é uma plataforma de atendimento, automação e gestão de conversas para empresas. Com ela, você pode centralizar canais de atendimento, organizar sua equipe, automatizar processos, utilizar recursos de IA, gerenciar contatos e acompanhar sua operação em um único ambiente."],
  ["Quais canais posso conectar à SharkZapp?", "A SharkZapp oferece integração com diferentes canais de comunicação, incluindo WhatsApp, Instagram, Mercado Livre e outros canais disponíveis na plataforma. Os recursos podem variar de acordo com cada canal, integração e configuração utilizada."],
  ["Posso conectar meu WhatsApp e ter vários atendentes?", "Sim. A SharkZapp permite estruturar uma operação com múltiplos usuários, setores, filas e atendentes, facilitando a distribuição e o gerenciamento das conversas. A disponibilidade e a forma de conexão do WhatsApp dependem do método de integração utilizado."],
  ["Posso automatizar meu atendimento?", "Sim. A SharkZapp permite criar automações, gatilhos, fluxos e chatbots para executar tarefas automaticamente. Você pode, por exemplo, automatizar respostas iniciais, direcionar clientes para setores, aplicar etiquetas, qualificar contatos, iniciar fluxos e encaminhar conversas para um atendente quando necessário."],
  ["A SharkZapp possui inteligência artificial?", "Sim. A SharkZapp possui recursos de inteligência artificial que podem auxiliar sua operação em tarefas como atendimento, respostas, qualificação e automação. Os recursos disponíveis podem variar conforme o plano, configuração e integração utilizada."],
  ["Preciso entender de programação para usar a SharkZapp?", "Não para as funções principais. A SharkZapp foi desenvolvida para permitir que empresas organizem seus atendimentos e configurem automações por meio de uma interface visual. Recursos mais avançados, como determinadas integrações, API e Webhooks, podem exigir configuração técnica adicional."],
  ["Como posso começar a usar a SharkZapp?", "É simples: escolha o plano adequado para sua operação, faça seu cadastro e configure os canais e usuários que deseja utilizar. Depois, você poderá estruturar seus setores, equipes, automações e fluxos de atendimento e começar a centralizar sua operação na SharkZapp."],
];

function Brand({ light = false }: { light?: boolean }) {
  return <a href="#inicio" className={`inline-flex items-center gap-2.5 font-extrabold text-[21px] tracking-normal ${light ? "text-hero-foreground" : "text-foreground"}`} aria-label="SharkZapp — início"><span className="grid size-9 place-items-center rounded-md bg-primary text-primary-foreground"><AudioLines size={21} strokeWidth={2.6} /></span>Shark<span className={light ? "text-electric" : "text-primary"}>Zapp</span></a>;
}
function SectionIntro({ eyebrow, title, children, center = false }: { eyebrow: string; title: string; children?: React.ReactNode; center?: boolean }) {
  return <div className={center ? "mx-auto max-w-2xl text-center" : "max-w-2xl"}><p className="mb-4 text-xs font-extrabold uppercase tracking-[0.16em] text-primary">{eyebrow}</p><h2 className="text-3xl font-extrabold leading-[1.16] sm:text-4xl lg:text-[44px]">{title}</h2>{children && <p className="mt-5 text-base leading-7 text-muted-foreground">{children}</p>}</div>;
}
function Cta({ children = "Começar agora", light = false, className = "" }: { children?: React.ReactNode; light?: boolean; className?: string }) {
  return <Button asChild size="lg" className={`h-12 px-6 font-bold shadow-lg shadow-primary/20 transition-transform hover:-translate-y-0.5 ${light ? "bg-background text-primary hover:bg-soft-blue" : ""} ${className}`}><a href="#planos">{children}<ArrowUpRight size={16} /></a></Button>;
}
function TinyBadge({ children, tone = "blue" }: { children: React.ReactNode; tone?: "blue" | "green" | "neutral" }) { return <span className={`inline-flex items-center rounded px-2 py-1 text-[10px] font-bold ${tone === "green" ? "bg-success/10 text-success" : tone === "neutral" ? "bg-muted text-muted-foreground" : "bg-soft-blue text-primary"}`}>{children}</span>; }
function Avatar({ name, color = "blue" }: { name: string; color?: "blue" | "green" | "gray" }) { return <span className={`grid size-8 shrink-0 place-items-center rounded-full text-[10px] font-bold ${color === "green" ? "bg-success/15 text-success" : color === "gray" ? "bg-muted text-muted-foreground" : "bg-soft-blue text-primary"}`}>{name.split(" ").map(v => v[0]).slice(0,2).join("")}</span>; }
function Metric({ label, value, icon: Icon }: { label: string; value: string; icon: LucideIcon }) { return <div className="rounded-md border border-border bg-card p-4"><div className="flex items-center justify-between text-[11px] text-muted-foreground"><span>{label}</span><Icon size={14} className="text-primary" /></div><b className="mt-3 block text-2xl tracking-normal text-foreground">{value}</b></div>; }
function InboxPreview({ compact = false }: { compact?: boolean }) {
  const [active, setActive] = useState(0);
  const conversations = [
    { name: "Mariana Costa", initial: "MC", channel: "WhatsApp", excerpt: "Gostaria de saber mais sobre os planos.", time: "Agora", tag: "Novo lead" },
    { name: "Rafael Almeida", initial: "RA", channel: "Instagram", excerpt: "Obrigado! Vou conferir as opções.", time: "12:42", tag: "Qualificado" },
    { name: "Camila Rocha", initial: "CR", channel: "Mercado Livre", excerpt: "Meu pedido já foi enviado?", time: "11:28", tag: "Suporte" },
    { name: "Pedro Martins", initial: "PM", channel: "E-mail", excerpt: "Podem me ajudar com uma dúvida?", time: "10:15", tag: "Em andamento" },
  ];
  const selected = conversations[active] ?? { name: "Mariana Costa", initial: "MC", channel: "WhatsApp", excerpt: "Gostaria de saber mais sobre os planos.", time: "Agora", tag: "Novo lead" };
  return <div className="overflow-hidden rounded-lg border border-border bg-card text-foreground shadow-2xl shadow-hero/15" aria-label="Prévia demonstrativa da caixa de entrada SharkZapp">
    <div className="flex h-10 items-center justify-between border-b border-border bg-surface px-4"><div className="flex items-center gap-2"><span className="size-2 rounded-full bg-destructive/70"/><span className="size-2 rounded-full bg-chart-4"/><span className="size-2 rounded-full bg-success"/><span className="ml-3 text-[10px] font-extrabold">SharkZapp <span className="font-medium text-muted-foreground">/ Caixa de entrada</span></span></div><span className="text-[10px] text-muted-foreground">Visão demonstrativa</span></div>
    <div className={`grid ${compact ? "min-h-[300px] grid-cols-[46px_minmax(125px,1fr)_minmax(180px,1.2fr)] sm:grid-cols-[52px_minmax(160px,0.8fr)_minmax(230px,1.3fr)]" : "min-h-[340px] grid-cols-[46px_minmax(130px,0.8fr)_minmax(190px,1.3fr)] sm:min-h-[420px] sm:grid-cols-[56px_minmax(200px,0.8fr)_minmax(250px,1.3fr)_minmax(150px,0.65fr)]"}`}>
      <div className="flex flex-col items-center gap-5 border-r border-border bg-hero py-5 text-hero-foreground/60"><span className="grid size-7 place-items-center rounded bg-primary text-primary-foreground"><AudioLines size={15}/></span><Inbox size={17} className="text-hero-foreground"/><Users size={17}/><KanbanSquare size={17}/><Workflow size={17}/><BarChart3 size={17}/><Settings2 size={17} className="mt-auto"/></div>
      <div className="min-w-0 border-r border-border"><div className="border-b border-border px-3 py-4 sm:px-4"><div className="flex items-center justify-between"><b className="text-xs sm:text-sm">Conversas</b><ListFilter size={14} className="text-muted-foreground"/></div><div className="mt-3 flex h-7 items-center gap-2 rounded border border-border bg-surface px-2 text-[10px] text-muted-foreground"><Search size={12}/> Buscar</div></div><div className="flex gap-2 overflow-hidden border-b border-border px-3 py-2 text-[9px] font-bold"><span className="text-primary">Todas</span><span className="text-muted-foreground">Não lidas</span></div>{conversations.map((c,i)=><button key={c.name} onClick={()=>setActive(i)} className={`flex w-full min-w-0 items-start gap-2 border-b border-border p-2.5 text-left transition-colors sm:p-3 ${active===i ? "bg-soft-blue/60" : "hover:bg-surface"}`}><Avatar name={c.initial}/><span className="min-w-0 flex-1"><span className="block truncate text-[10px] font-bold sm:text-[11px]">{c.name}</span><span className="block truncate text-[9px] text-muted-foreground">{c.excerpt}</span><span className="mt-1 block text-[8px] text-primary">{c.channel}</span></span></button>)}</div>
      <div className="flex min-w-0 flex-col"><div className="flex items-center gap-2 border-b border-border p-3"><Avatar name={selected.initial}/><div className="min-w-0 flex-1"><b className="block truncate text-[10px] sm:text-xs">{selected.name}</b><span className="block text-[9px] text-muted-foreground">{selected.channel} · Em atendimento</span></div><PhoneCall size={14} className="hidden text-muted-foreground sm:block"/></div><div className="flex flex-1 flex-col gap-3 bg-surface/50 p-3 sm:p-5"><span className="mx-auto text-[9px] text-muted-foreground">Hoje</span><div className="max-w-[92%] self-start rounded-md rounded-tl-none border border-border bg-card px-3 py-2 text-[10px] leading-4 shadow-sm">Olá! {active===0 ? "Gostaria de saber mais sobre os planos." : selected.excerpt}</div><div className="max-w-[92%] self-end rounded-md rounded-tr-none bg-soft-blue px-3 py-2 text-[10px] leading-4">Olá, {selected.name.split(" ")[0]}! Claro, posso te ajudar com isso.</div><span className="self-end text-[8px] text-muted-foreground">Enviado · agora</span></div><div className="flex items-center gap-2 border-t border-border p-2 sm:p-3"><span className="flex-1 truncate rounded border border-border px-2 py-2 text-[9px] text-muted-foreground">Escreva uma mensagem...</span><span className="grid size-7 shrink-0 place-items-center rounded bg-primary text-primary-foreground"><Send size={12}/></span></div></div>
      {!compact && <div className="hidden border-l border-border p-3 sm:block"><p className="text-[10px] font-bold">Informações do cliente</p><div className="mt-5 flex flex-col items-center gap-2"><Avatar name={selected.initial}/><b className="text-[10px]">{selected.name}</b><span className="text-[9px] text-muted-foreground">Contato ativo</span></div><div className="mt-5 space-y-3 border-t border-border pt-4 text-[9px]"><p className="text-muted-foreground">Atendente <b className="block pt-1 text-foreground">Ana · Vendas</b></p><p className="text-muted-foreground">Setor <b className="block pt-1 text-foreground">Comercial</b></p><p className="text-muted-foreground">Etiquetas <span className="mt-1 block"><TinyBadge>{selected.tag}</TinyBadge></span></p><p className="text-muted-foreground">Histórico <b className="block pt-1 text-foreground">Conversa atual</b></p></div></div>}
    </div>
  </div>;
}
function FlowPreview({ vertical = false }: { vertical?: boolean }) { const steps = ["Novo contato", "Identificação", "Resposta automática", "Qualificação", "Etiqueta", "Distribuição", "Atendente", "Follow-up"]; return <div className={`grid gap-2 ${vertical ? "max-w-sm grid-cols-1" : "grid-cols-2 sm:grid-cols-4"}`}>{steps.map((s,i)=><div key={s} className="relative flex items-center gap-3 rounded-md border border-border bg-card p-3 shadow-sm"><span className={`grid size-7 shrink-0 place-items-center rounded text-[10px] font-extrabold ${i===0 ? "bg-primary text-primary-foreground" : "bg-soft-blue text-primary"}`}>{String(i+1).padStart(2,"0")}</span><span className="text-xs font-bold">{s}</span>{i<steps.length-1 && !vertical && <ArrowRight size={12} className="flow-pulse absolute -right-2.5 z-10 hidden text-primary sm:block"/>}</div>)}</div>; }
function CrmPreview() { const columns: [string, ...string[]][] = [["Novo lead", "Mariana Costa", "Lucas Ribeiro"], ["Contato", "Bianca Oliveira"], ["Qualificado", "Rafael Almeida"], ["Proposta", "Fernanda Lima"], ["Negociação", "Eduardo Santos"], ["Cliente", "Patrícia Silva"]]; return <div className="overflow-x-auto rounded-lg border border-border bg-surface p-3"><div className="grid min-w-[660px] grid-cols-6 gap-2">{columns.map(([title,...names],i)=><div key={title} className="min-h-44"><div className="mb-2 flex items-center justify-between rounded bg-soft-blue px-2 py-2 text-[10px] font-bold"><span>{title}</span><span className="text-primary">{names.length}</span></div>{names.map((name,j)=><div key={name} className="mb-2 rounded border border-border bg-card p-2 shadow-sm"><div className="mb-2 flex items-center gap-1.5"><Avatar name={name}/><b className="text-[9px] leading-tight">{name}</b></div><TinyBadge tone={i>=4 ? "green" : "blue"}>{j===0 ? "WhatsApp" : "Instagram"}</TinyBadge></div>)}</div>)}</div></div>; }
function TeamPreview() { return <div className="grid gap-3 sm:grid-cols-2">{[["Ana", "Vendas", "Disponível", "blue"], ["Carlos", "Suporte", "Em atendimento", "green"], ["Marina", "Financeiro", "Disponível", "blue"], ["João", "Pós-venda", "Em atendimento", "green"]].map(([name,sector,status,color])=><div key={name} className="flex items-center gap-3 rounded-md border border-border bg-card p-4"><Avatar name={name} color={color as "blue" | "green"}/><div className="flex-1"><b className="text-sm">{name}</b><p className="text-xs text-muted-foreground">{sector}</p></div><TinyBadge tone={status==="Disponível" ? "green" : "neutral"}>{status}</TinyBadge></div>)}<div className="flex items-center gap-2 rounded-md border border-primary/20 bg-soft-blue p-4 text-xs text-primary sm:col-span-2"><GitBranch size={16}/> Distribuição automática por setor e fila</div></div>; }
function ReportPreview() { return <div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3"><Metric label="Atendimentos" value="1.248" icon={MessagesSquare}/><Metric label="Tempo médio de resposta" value="4m 32s" icon={Clock3}/><Metric label="Conversas resolvidas" value="987" icon={Check}/><Metric label="Leads" value="312" icon={Users}/><Metric label="Conversões" value="46" icon={ArrowUpRight}/><Metric label="Agentes ativos" value="08" icon={Headphones}/></div><div className="mt-3 rounded-md border border-border bg-card p-4"><div className="flex justify-between text-xs font-bold"><span>Atendimentos por agente</span><span className="font-normal text-muted-foreground">Últimos 7 dias</span></div><div className="mt-6 flex h-24 items-end justify-around gap-2 border-b border-border">{[42,68,53,86,60,76,49,91,65,82,57,72].map((v,i)=><div key={i} className="w-full max-w-6 rounded-t bg-primary/75" style={{height:`${v}%`}}/>)}</div></div><p className="mt-3 text-[10px] text-muted-foreground">Dados demonstrativos</p></div>; }
function InstagramPreview() { return <div className="mx-auto max-w-sm overflow-hidden rounded-lg border border-border bg-card shadow-xl"><div className="flex items-center gap-3 border-b border-border p-4"><span className="grid size-9 place-items-center rounded-full bg-soft-blue text-primary"><Instagram size={19}/></span><div><b className="text-sm">Direct · Instagram</b><p className="text-[10px] text-muted-foreground">Conversa demonstrativa</p></div></div><div className="space-y-4 bg-surface/60 px-5 py-8 text-xs"><p className="w-fit max-w-[85%] rounded-lg rounded-bl-none bg-card p-3 shadow-sm">Oi! Vocês podem me ajudar com uma dúvida?</p><p className="ml-auto w-fit max-w-[85%] rounded-lg rounded-br-none bg-soft-blue p-3">Olá! Claro. Me conta como podemos ajudar você.</p><p className="w-fit max-w-[85%] rounded-lg rounded-bl-none bg-card p-3 shadow-sm">Quero entender como funciona o atendimento com vários agentes.</p><div className="flex gap-2"><TinyBadge>Vendas</TinyBadge><TinyBadge tone="green">Em atendimento</TinyBadge></div></div><div className="border-t border-border p-4 text-xs text-muted-foreground">Responder no direct...</div></div>; }

function Landing() {
  const [scrolled, setScrolled] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [billing, setBilling] = useState<"mensal"|"anual">("mensal");
  const [dialog, setDialog] = useState<null | "entrar" | "plano" | "legal" | "social">(null);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 24); onScroll(); window.addEventListener("scroll",onScroll,{passive:true}); return ()=>window.removeEventListener("scroll",onScroll); },[]);
  return <div className="overflow-x-clip bg-background text-foreground">
    <header className={`fixed inset-x-0 top-0 z-50 transition-all duration-300 ${scrolled || menuOpen ? "border-b border-border bg-background/95 shadow-sm backdrop-blur-xl" : "bg-background"}`}><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between gap-4 px-5 lg:px-8"><Brand/><nav className="hidden items-center gap-5 xl:flex" aria-label="Navegação principal">{nav.map(([label,href])=><a key={href} href={href} className="text-xs font-semibold text-muted-foreground transition-colors hover:text-primary">{label}</a>)}</nav><div className="hidden items-center gap-3 md:flex"><Button variant="ghost" onClick={()=>setDialog("entrar")}>Entrar</Button><Cta/></div><Button variant="ghost" size="icon" className="md:hidden" aria-label={menuOpen ? "Fechar menu" : "Abrir menu"} aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen ? <X/> : <Menu/>}</Button></div>{menuOpen && <nav className="border-t border-border bg-background px-5 pb-6 pt-3 shadow-lg md:hidden" aria-label="Navegação mobile">{nav.map(([label,href])=><a onClick={()=>setMenuOpen(false)} key={href} href={href} className="block border-b border-border py-3 text-sm font-semibold">{label}</a>)}<div className="mt-5 flex gap-3"><Button variant="outline" onClick={()=>{setDialog("entrar");setMenuOpen(false)}}>Entrar</Button><Cta/></div></nav>}</header>
    <main>
      <section id="inicio" className="relative bg-hero pb-10 pt-28 text-hero-foreground sm:pb-16 sm:pt-36"><div className="hero-glow pointer-events-none absolute inset-0"/><div className="hero-grid pointer-events-none absolute inset-0"/><div className="relative mx-auto max-w-7xl px-5 lg:px-8"><div className="mx-auto max-w-4xl text-center"><div className="animate-rise mb-7 inline-flex items-center gap-2 rounded-full border border-hero-foreground/15 bg-hero-foreground/5 px-4 py-2 text-[11px] font-bold text-hero-foreground/85"><span className="size-1.5 rounded-full bg-success"/> Atendimento, automação e gestão em um só lugar</div><h1 className="animate-rise text-[38px] font-extrabold leading-[1.12] sm:text-5xl lg:text-[64px]">Seu atendimento.<br/><span className="text-electric">Mais rápido.</span> Mais inteligente.<br/>Mais automático.</h1><p className="animate-rise-delay mx-auto mt-6 max-w-2xl text-sm leading-7 text-hero-foreground/70 sm:text-base">Centralize WhatsApp, Instagram, Mercado Livre e outros canais em uma única plataforma. Automatize conversas, organize sua equipe e transforme sua operação.</p><div className="animate-rise-delay mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row"><Cta className="w-full sm:w-auto"/><Button asChild size="lg" variant="outline" className="h-12 w-full border-hero-foreground/25 bg-hero-foreground/5 px-6 text-hero-foreground hover:bg-hero-foreground/10 hover:text-hero-foreground sm:w-auto"><a href="#demonstracao">Conhecer a plataforma <ArrowRight size={16}/></a></Button></div><p className="mt-7 text-[11px] font-semibold text-hero-foreground/50">Atendimento <span className="mx-1">•</span> Automação <span className="mx-1">•</span> IA <span className="mx-1">•</span> CRM <span className="mx-1">•</span> Omnichannel</p></div><div className="relative mx-auto mt-14 max-w-6xl sm:mt-16"><div className="relative z-10"><InboxPreview/><div className="float-soft absolute -left-3 top-16 hidden items-center gap-2 rounded-md border border-border bg-card px-3 py-2 text-[10px] font-bold text-foreground shadow-lg lg:flex"><span className="grid size-6 place-items-center rounded bg-soft-blue text-primary"><Bell size={13}/></span>Novo atendimento</div><div className="float-soft absolute -right-4 top-20 hidden items-center gap-2 rounded-md border border-border bg-card px-3 py-2 text-[10px] font-bold text-foreground shadow-lg lg:flex"><span className="size-2 rounded-full bg-success"/> Instagram conectado</div><div className="float-soft absolute -right-7 bottom-14 hidden items-center gap-2 rounded-md border border-border bg-card px-3 py-2 text-[10px] font-bold text-foreground shadow-lg lg:flex"><Sparkles size={14} className="text-primary"/> Lead qualificado</div></div></div></div></section>
      <section id="canais" className="border-b border-border bg-background pb-16 pt-20 sm:pt-24"><div className="mx-auto max-w-7xl px-5 text-center lg:px-8"><p className="text-xs font-bold uppercase tracking-[0.15em] text-primary">Canais conectados</p><h2 className="mx-auto mt-3 max-w-xl text-2xl font-extrabold sm:text-3xl">Todos os canais importantes da sua operação, em um só lugar.</h2><div className="mt-9 flex flex-wrap justify-center gap-2">{channels.map(c=><span key={c} className="rounded-md border border-border bg-surface px-4 py-2.5 text-xs font-bold transition-colors hover:border-primary/40 hover:bg-soft-blue">{c}</span>)}</div><p className="mt-6 text-xs text-muted-foreground">Os recursos disponíveis podem variar conforme o canal e a integração utilizada.</p></div></section>
      <section className="bg-surface py-20 sm:py-28"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 lg:grid-cols-[.85fr_1.15fr] lg:gap-20 lg:px-8"><div><SectionIntro eyebrow="O desafio" title="Seu atendimento não deveria ser uma bagunça.">Quando tudo acontece em lugares diferentes, manter o contexto fica mais difícil.</SectionIntro><p className="mt-8 text-lg font-extrabold text-primary">É para simplificar tudo isso que existe a SharkZapp.</p></div><div className="grid grid-cols-2 gap-3">{["Conversas espalhadas", "Leads esperando resposta", "Equipe desorganizada", "Processos manuais", "Perguntas repetitivas", "Falta de acompanhamento", "Informações perdidas", "Oportunidades desperdiçadas"].map((t,i)=><div key={t} className="flex min-h-20 items-center gap-3 rounded-md border border-border bg-card p-4 text-xs font-bold shadow-sm sm:text-sm"><span className="grid size-7 shrink-0 place-items-center rounded bg-soft-blue text-primary">{String(i+1).padStart(2,"0")}</span>{t}</div>)}</div></div></section>
      <section className="py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionIntro eyebrow="O que muda" title="Mais controle. Menos trabalho manual."/><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{([["Atenda mais rápido","Tenha suas conversas organizadas e facilite o trabalho da equipe.",Clock3],["Automatize tarefas","Deixe processos repetitivos funcionando automaticamente.",Zap],["Organize sua equipe","Distribua atendimentos entre usuários, setores e filas.",Users],["Centralize seus canais","Tenha uma visão unificada da sua operação.",MessagesSquare],["Conheça seus clientes","Organize contatos, histórico, etiquetas e informações.",UserRoundCheck],["Acompanhe sua operação","Visualize indicadores e acompanhe o desempenho.",BarChart3]] as [string, string, LucideIcon][]).map(([title,desc,Icon])=><div key={title as string} className="rounded-md border border-border bg-card p-6 transition-all hover:-translate-y-1 hover:border-primary/30 hover:shadow-lg"><span className="grid size-10 place-items-center rounded-md bg-soft-blue text-primary"><Icon size={20}/></span><h3 className="mt-6 text-base font-extrabold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{desc as string}</p></div>)}</div></div></section>
      <section id="funcionalidades" className="bg-surface py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionIntro eyebrow="Funcionalidades" title="Tudo conectado à sua operação.">Recursos para dar contexto a cada conversa e ritmo a cada equipe.</SectionIntro><div className="mt-10 grid grid-cols-2 gap-3 md:grid-cols-4">{features.map(([title,desc,Icon])=><div key={title} className="group rounded-md border border-border bg-card p-4 transition-all hover:-translate-y-1 hover:border-primary/40 hover:shadow-md sm:p-5"><Icon size={20} className="text-primary transition-transform group-hover:scale-110"/><h3 className="mt-5 text-sm font-extrabold">{title}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{desc}</p></div>)}</div></div></section>
      <section id="demonstracao" className="py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionIntro eyebrow="Por dentro da plataforma" title="Veja como a SharkZapp funciona." center>Uma visão visual de como conversas, automações e pessoas se encontram no mesmo lugar.</SectionIntro><Tabs defaultValue="atendimento" className="mt-10"><div className="overflow-x-auto pb-2"><TabsList className="mx-auto flex h-auto w-max gap-1 bg-surface p-1.5"><TabsTrigger value="atendimento" className="px-4 py-2.5">Atendimento</TabsTrigger><TabsTrigger value="automacao" className="px-4 py-2.5">Automação</TabsTrigger><TabsTrigger value="crm" className="px-4 py-2.5">CRM</TabsTrigger><TabsTrigger value="equipe" className="px-4 py-2.5">Equipe</TabsTrigger><TabsTrigger value="relatorios" className="px-4 py-2.5">Relatórios</TabsTrigger></TabsList></div><div className="mt-6 min-h-[390px] rounded-lg border border-border bg-surface p-3 sm:p-6"><TabsContent value="atendimento" className="mt-0"><InboxPreview compact/></TabsContent><TabsContent value="automacao" className="mt-0"><div className="mb-6 flex items-center gap-3"><Workflow className="text-primary"/><div><h3 className="text-sm font-bold">Fluxo de atendimento</h3><p className="text-xs text-muted-foreground">Da primeira mensagem ao acompanhamento.</p></div></div><FlowPreview/></TabsContent><TabsContent value="crm" className="mt-0"><div className="mb-5 text-sm font-bold">Pipeline de oportunidades</div><CrmPreview/></TabsContent><TabsContent value="equipe" className="mt-0"><div className="mb-5 text-sm font-bold">Equipe e distribuição</div><TeamPreview/></TabsContent><TabsContent value="relatorios" className="mt-0"><ReportPreview/></TabsContent></div></Tabs><p className="mt-3 text-center text-xs text-muted-foreground">Interfaces e dados demonstrativos para apresentação do produto.</p></div></section>
      <section className="bg-hero py-20 text-hero-foreground sm:py-28"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 lg:grid-cols-2 lg:gap-16 lg:px-8"><div><p className="mb-4 text-xs font-extrabold uppercase tracking-[0.16em] text-electric">WhatsApp</p><h2 className="text-3xl font-extrabold leading-tight sm:text-4xl">Transforme o WhatsApp em uma central de atendimento.</h2><p className="mt-5 leading-7 text-hero-foreground/65">Estruture sua operação com pessoas, processos e contexto em cada conversa.</p><div className="mt-8 grid grid-cols-2 gap-3">{["Multiatendimento","Filas","Setores","Chatbots","Automação","IA","CRM","Tags","Histórico","Agendamento","Campanhas","API"].map(s=><div key={s} className="flex items-center gap-2 text-sm"><Check size={15} className="text-electric"/>{s}</div>)}</div><p className="mt-8 text-xs leading-5 text-hero-foreground/50">Os recursos e as formas de conexão dependem da integração utilizada.</p></div><InboxPreview compact/></div></section>
      <section className="py-20 sm:py-28"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 lg:grid-cols-2 lg:gap-20 lg:px-8"><InstagramPreview/><div><SectionIntro eyebrow="Instagram" title="Seus directs também fazem parte da operação.">Atenda com mais organização, mantenha o histórico acessível e acompanhe cada conversa junto da sua equipe.</SectionIntro><div className="mt-7 flex flex-wrap gap-2">{["Atendimento","Organização","Histórico","Automações","Tags","Equipe","IA quando disponível"].map(s=><TinyBadge key={s}>{s}</TinyBadge>)}</div></div></div></section>
      <section className="bg-surface py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionIntro eyebrow="Multicanal" title="Mais canais. Menos abas.">Conecte os canais disponíveis para sua operação e gerencie suas conversas de forma centralizada.</SectionIntro><div className="mt-9 grid grid-cols-2 gap-3 sm:grid-cols-5">{channels.map((c,i)=><div key={c} className="flex items-center gap-3 rounded-md border border-border bg-card p-4 text-xs font-bold transition-colors hover:border-primary/40"><span className="grid size-8 shrink-0 place-items-center rounded bg-soft-blue text-primary">{i===1?<Instagram size={16}/>:i===5?<Mail size={16}/>:<MessageCircle size={16}/>}</span>{c}</div>)}</div><p className="mt-5 text-xs text-muted-foreground">Os recursos disponíveis podem variar conforme o canal e a integração utilizada.</p></div></section>
      <section className="py-20 sm:py-28"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 lg:grid-cols-[.85fr_1.15fr] lg:gap-20 lg:px-8"><div><SectionIntro eyebrow="Automação" title="Enquanto sua equipe trabalha, a SharkZapp trabalha também.">Crie jornadas para responder, qualificar e direcionar conversas conforme a configuração da sua operação.</SectionIntro><div className="mt-7 flex items-center gap-2 text-sm font-bold text-primary"><Zap size={16}/> Automação executada <ArrowRight size={14}/></div><div className="mt-3 flex items-center gap-2 text-sm font-bold text-primary"><GitBranch size={16}/> Cliente encaminhado para Vendas</div></div><div className="rounded-lg border border-border bg-surface p-5 sm:p-8"><div className="mb-5 flex items-center justify-between"><span className="text-sm font-bold">Fluxo de atendimento</span><TinyBadge tone="green">Ativo · demonstração</TinyBadge></div><FlowPreview/></div></div></section>
      <section className="bg-soft-blue/45 py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionIntro eyebrow="Inteligência artificial" title="Inteligência artificial para acelerar seu atendimento.">A IA pode ajudar sua equipe a acelerar tarefas, organizar informações e automatizar etapas do atendimento.</SectionIntro><div className="mt-10 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{["Responder","Qualificar","Organizar","Resumir","Encaminhar","Automatizar"].map((s,i)=><div key={s} className="rounded-md border border-border bg-card p-5"><span className="grid size-9 place-items-center rounded bg-soft-blue text-primary"><Sparkles size={17}/></span><p className="mt-5 text-sm font-bold">{s}</p><span className="mt-2 block text-[10px] text-muted-foreground">0{i+1} / IA</span></div>)}</div></div></section>
      <section className="py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionIntro eyebrow="CRM" title="Cada conversa conta.">Acompanhe oportunidades do primeiro contato até a próxima etapa.</SectionIntro><div className="mt-9"><CrmPreview/></div></div></section>
      <section className="bg-surface py-20 sm:py-28"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 lg:grid-cols-2 lg:gap-20 lg:px-8"><div><SectionIntro eyebrow="Gestão de equipe" title="Uma equipe inteira. Uma operação organizada.">Distribua atendimentos por filas e setores para manter cada conversa com a pessoa certa.</SectionIntro></div><TeamPreview/></div></section>
      <section className="py-20 sm:py-28"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 lg:grid-cols-[.8fr_1.2fr] lg:gap-20 lg:px-8"><div><SectionIntro eyebrow="Indicadores" title="Acompanhe o que acontece, não apenas o que chega.">Atendimentos, tempos de resposta, conversas resolvidas e a atividade da equipe em uma visão mais clara.</SectionIntro><p className="mt-5 inline-flex rounded bg-soft-blue px-3 py-1.5 text-xs font-bold text-primary">Dados demonstrativos</p></div><ReportPreview/></div></section>
      <section className="bg-hero py-20 text-hero-foreground sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="mb-4 text-xs font-extrabold uppercase tracking-[0.16em] text-electric">Estrutura para crescer</p><h2 className="max-w-xl text-3xl font-extrabold leading-tight sm:text-4xl">Uma plataforma pensada para sua operação.</h2><div className="mt-10 grid grid-cols-2 gap-3 md:grid-cols-4">{([["Controle de usuários",Users],["Organização por setores",Layers3],["Permissões",ShieldCheck],["Histórico",Clock3],["Gestão centralizada",LayoutDashboard],["Integrações",PlugZap],["API",Code2],["Webhooks",Webhook]] as [string, LucideIcon][]).map(([s,Icon])=><div key={s as string} className="rounded-md border border-hero-foreground/15 bg-hero-foreground/5 p-5"><Icon size={20} className="text-electric"/><h3 className="mt-5 text-sm font-bold">{s as string}</h3></div>)}</div></div></section>
      <section className="py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionIntro eyebrow="Para quem é" title="Feita para operações que querem crescer."/><div className="mt-10 flex flex-wrap gap-3">{["Empresas","E-commerces","Agências","Infoprodutores","Prestadores de serviço","Times comerciais","Lojas","Marketplaces","Profissionais de atendimento"].map(s=><span key={s} className="rounded-md border border-border bg-surface px-5 py-3 text-sm font-bold">{s}</span>)}</div></div></section>
      <section id="como-funciona" className="bg-surface py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionIntro eyebrow="Como funciona" title="Do primeiro canal à operação conectada."/><div className="mt-10 grid gap-5 md:grid-cols-3">{([["01","Conecte seus canais","Reúna as conversas dos canais disponíveis para sua operação.",PlugZap],["02","Configure sua operação","Organize usuários, setores, filas e automações.",Settings2],["03","Comece a atender","Acompanhe conversas e trabalhe com mais contexto.",MessagesSquare]] as [string, string, string, LucideIcon][]).map(([n,title,desc,Icon])=><div key={n as string} className="rounded-md border border-border bg-card p-6"><div className="flex items-center justify-between"><span className="text-4xl font-extrabold text-primary/25">{n as string}</span><Icon size={21} className="text-primary"/></div><h3 className="mt-6 text-lg font-extrabold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{desc as string}</p></div>)}</div></div></section>
      <section className="py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionIntro eyebrow="Uma visão, mais possibilidades" title="Menos ferramentas. Mais controle." center/><div className="mx-auto mt-10 grid max-w-4xl gap-4 sm:grid-cols-2"><div className="rounded-lg border border-border bg-surface p-6 sm:p-8"><p className="mb-6 text-xs font-extrabold uppercase tracking-[0.15em] text-muted-foreground">Antes</p><div className="space-y-3">{["WhatsApp","Instagram","Planilhas","CRM separado","Chatbot separado","Automação separada"].map(s=><p key={s} className="flex items-center gap-3 border-b border-border pb-3 text-sm text-muted-foreground"><span className="size-1.5 rounded-full bg-muted-foreground/50"/>{s}</p>)}</div></div><div className="rounded-lg border border-primary/30 bg-soft-blue p-6 sm:p-8"><p className="mb-6 text-xs font-extrabold uppercase tracking-[0.15em] text-primary">SharkZapp</p><div className="grid grid-cols-2 gap-3">{["Atendimento","Automação","CRM","IA","Equipe","Relatórios","Canais"].map(s=><p key={s} className="flex items-center gap-2 text-sm font-bold"><Check size={14} className="text-primary"/>{s}</p>)}</div></div></div></div></section>
      <section className="bg-surface py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionIntro eyebrow="A plataforma em foco" title="Uma plataforma feita para simplificar sua operação.">Conheça diferentes visões de uma mesma rotina conectada.</SectionIntro><div className="mt-10 grid gap-4 lg:grid-cols-[1.25fr_.75fr]"><div><InboxPreview compact/></div><div className="grid gap-4"><div className="rounded-md border border-border bg-card p-5"><p className="mb-4 text-xs font-bold">Dashboard · Dados demonstrativos</p><div className="grid grid-cols-2 gap-2"><Metric label="Conversas" value="1.248" icon={MessagesSquare}/><Metric label="Leads" value="312" icon={Users}/></div></div><div className="rounded-md border border-border bg-card p-5"><p className="mb-4 text-xs font-bold">Automação · Fluxo ativo</p><div className="flex flex-wrap items-center gap-2 text-[10px] font-bold"><TinyBadge>Novo contato</TinyBadge><ArrowRight size={12}/><TinyBadge>Qualificação</TinyBadge><ArrowRight size={12}/><TinyBadge tone="green">Atendente</TinyBadge></div></div></div></div><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="rounded-md border border-border bg-card p-5"><p className="mb-4 text-xs font-bold">CRM · Etapas</p><div className="flex flex-wrap gap-2">{["Novo lead","Contato","Qualificado","Proposta","Cliente"].map(s=><TinyBadge key={s}>{s}</TinyBadge>)}</div></div><div className="rounded-md border border-border bg-card p-5"><p className="mb-4 text-xs font-bold">Relatórios · Dados demonstrativos</p><div className="flex h-16 items-end gap-2">{[40,72,53,85,63,91,72,82,56,78].map((v,i)=><div key={i} className="w-full rounded-t bg-primary/70" style={{height:`${v}%`}}/>)}</div></div></div></div></section>
      <section id="planos" className="py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionIntro eyebrow="Planos" title="Escolha o plano para sua operação." center>Encontre a configuração que faz sentido para o momento da sua equipe.</SectionIntro><div className="mt-8 flex justify-center"><div className="inline-flex rounded-md border border-border bg-surface p-1" role="group" aria-label="Período de cobrança"><Button size="sm" variant={billing==="mensal"?"default":"ghost"} onClick={()=>setBilling("mensal")}>Mensal</Button><Button size="sm" variant={billing==="anual"?"default":"ghost"} onClick={()=>setBilling("anual")}>Anual</Button></div></div><div className="mt-9 grid gap-4 lg:grid-cols-3">{[["Starter","Para começar com uma operação organizada.",["Inbox unificado","Gestão de conversas","Usuários e setores","Histórico de atendimento"]],["Pro","Para equipes que buscam mais automação.",["Tudo do Starter","Automações e fluxos","CRM e etiquetas","Indicadores da operação"]],["Enterprise","Para operações com necessidades específicas.",["Tudo do Pro","Configuração personalizada","Integrações e API","Estrutura para múltiplas equipes"]]].map(([name,desc,items],i)=><div key={name as string} className={`relative flex flex-col rounded-lg border p-7 ${i===1 ? "border-primary bg-soft-blue/35 shadow-xl shadow-primary/10" : "border-border bg-card"}`}>{i===1 && <span className="absolute -top-3 left-6 rounded bg-primary px-3 py-1 text-[10px] font-bold text-primary-foreground">Mais escolhido</span>}<h3 className="text-xl font-extrabold">{name as string}</h3><p className="mt-2 min-h-12 text-sm text-muted-foreground">{desc as string}</p><div className="mt-6 border-b border-border pb-6"><p className="text-2xl font-extrabold">Sob consulta</p><p className="mt-1 text-xs text-muted-foreground">{billing === "mensal" ? "Condição mensal" : "Condição anual"} · valores a definir</p></div><div className="flex-1 space-y-4 py-7">{(items as string[]).map(s=><div key={s} className="flex items-center gap-3 text-sm"><Check size={16} className="shrink-0 text-primary"/>{s}</div>)}</div><Button className="h-11 w-full" variant={i===1?"default":"outline"} onClick={()=>setDialog("plano")}>Consultar plano <ArrowRight size={16}/></Button></div>)}</div><p className="mt-5 text-center text-xs text-muted-foreground">Valores e disponibilidade de recursos sujeitos à confirmação comercial. Nenhum preço foi definido nesta apresentação.</p></div></section>
      <section className="bg-surface py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionIntro eyebrow="Para cada etapa" title="Pensando se a SharkZapp é para você?"/><div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["Minha equipe é pequena.","Ainda estou começando.","Tenho vários canais.","Preciso automatizar tarefas.","Quero centralizar meus atendimentos.","Preciso integrar com outros sistemas."].map(s=><div key={s} className="flex items-center gap-3 rounded-md border border-border bg-card p-5 text-sm font-bold"><CircleHelp size={18} className="shrink-0 text-primary"/>{s}</div>)}</div><p className="mt-7 max-w-2xl text-sm leading-6 text-muted-foreground">A plataforma pode ser configurada conforme a necessidade da sua operação. A disponibilidade de cada recurso depende do plano e das integrações utilizadas.</p></div></section>
      <section id="faq" className="py-20 sm:py-28"><div className="mx-auto max-w-3xl px-5"><SectionIntro eyebrow="Perguntas frequentes" title="Dúvidas? Vamos direto ao ponto." center/><Accordion type="single" collapsible className="mt-10 border-t border-border">{faqs.map(([q,a],i)=><AccordionItem value={`faq-${i}`} key={q}><AccordionTrigger className="py-5 text-left text-sm font-bold hover:no-underline sm:text-base">{q}</AccordionTrigger><AccordionContent className="pb-5 text-sm leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>
      <section className="relative overflow-hidden bg-primary py-20 text-primary-foreground sm:py-28"><div className="hero-glow pointer-events-none absolute inset-0"/><div className="relative mx-auto max-w-4xl px-5 text-center"><h2 className="text-3xl font-extrabold leading-tight sm:text-5xl">Seu atendimento merece uma estrutura melhor.</h2><p className="mt-5 text-lg font-semibold text-primary-foreground/80">Centralize. Automatize. Escale.</p><div className="mt-8"><Cta light/></div><p className="mt-8 text-xs text-primary-foreground/70">SharkZapp — atendimento e automação para uma operação mais inteligente.</p></div></section>
    </main>
    <footer className="bg-hero pb-28 pt-16 text-hero-foreground sm:pb-16"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-10 border-b border-hero-foreground/15 pb-12 sm:grid-cols-2 lg:grid-cols-[2fr_1fr_1fr_1fr]"><div><Brand light/><p className="mt-5 max-w-xs text-sm leading-6 text-hero-foreground/55">Atendimento, automação e gestão em um só lugar.</p></div><div><h3 className="mb-5 text-sm font-bold">Produto</h3><div className="space-y-3 text-sm text-hero-foreground/55"><a className="block hover:text-hero-foreground" href="#funcionalidades">Funcionalidades</a><a className="block hover:text-hero-foreground" href="#canais">Canais</a><a className="block hover:text-hero-foreground" href="#planos">Planos</a><a className="block hover:text-hero-foreground" href="#faq">FAQ</a></div></div><div><h3 className="mb-5 text-sm font-bold">Empresa</h3><div className="space-y-3 text-sm text-hero-foreground/55"><a className="block hover:text-hero-foreground" href="#como-funciona">Sobre</a><button className="block cursor-pointer hover:text-hero-foreground" onClick={()=>setDialog("plano")}>Contato</button><button className="block cursor-pointer hover:text-hero-foreground" onClick={()=>setDialog("plano")}>Suporte</button></div></div><div><h3 className="mb-5 text-sm font-bold">Legal & redes</h3><div className="space-y-3 text-sm text-hero-foreground/55"><button className="block cursor-pointer hover:text-hero-foreground" onClick={()=>setDialog("legal")}>Termos de Uso</button><button className="block cursor-pointer hover:text-hero-foreground" onClick={()=>setDialog("legal")}>Política de Privacidade</button><div className="flex flex-wrap gap-x-4 gap-y-2 pt-2">{["Instagram","YouTube","LinkedIn"].map(s=><button key={s} className="cursor-pointer hover:text-hero-foreground" onClick={()=>setDialog("social")}>{s}</button>)}</div></div></div></div><div className="flex flex-col justify-between gap-3 pt-7 text-xs text-hero-foreground/45 sm:flex-row"><span>© 2026 SharkZapp. Todos os direitos reservados.</span><span>Atendimento e automação para uma operação mais inteligente.</span></div></div></footer>
    <div className="fixed bottom-5 right-5 z-40 hidden sm:block"><Cta className="shadow-xl shadow-primary/25"/></div><div className="fixed inset-x-0 bottom-0 z-40 border-t border-border bg-background/95 p-3 backdrop-blur-xl sm:hidden"><Cta className="w-full"/></div>
    <Dialog open={dialog!==null} onOpenChange={open=>!open&&setDialog(null)}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>{dialog==="entrar"?"Acesso à plataforma":dialog==="plano"?"Fale sobre sua operação":dialog==="legal"?"Documento ainda não disponível":"Perfil ainda não vinculado"}</DialogTitle><DialogDescription className="pt-3 leading-6">{dialog==="entrar"?"O endereço de acesso da SharkZapp ainda não foi informado. Assim que estiver disponível, o botão Entrar poderá levar você diretamente à plataforma.":dialog==="plano"?"Os valores e o canal de contato comercial ainda não foram fornecidos. A escolha do plano e o cadastro poderão ser concluídos quando esses dados forem configurados.":dialog==="legal"?"O documento oficial ainda não foi fornecido. Nenhum texto jurídico provisório foi publicado como se fosse definitivo.":"O endereço oficial desta rede social ainda não foi fornecido."}</DialogDescription></DialogHeader><Button onClick={()=>setDialog(null)} className="mt-3">Entendi</Button></DialogContent></Dialog>
  </div>;
}
